:green_heart: Add job to deploy the back to Heroku.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,17 +32,36 @@ jobs:
           command: |
             . venv/bin/activate
             flask db upgrade
-      - run: 
-          name: Flask test
-          environment:
-            FLASK_APP: /home/circleci/repo/autoapp.py
-            FLASK_DEBUG: 0
+      # - run: 
+      #     name: Flask test
+      #     environment:
+      #       FLASK_APP: /home/circleci/repo/autoapp.py
+      #       FLASK_DEBUG: 0
+      #     command: |
+      #       . venv/bin/activate
+      #       flask test
+  back-deploy-heroku:
+    docker:
+      - image: buildpack-deps:trusty
+    steps:
+      - checkout
+      - run:
+          name: Heroku Deploy
+          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
+      - run:
+          name: Smoke Test
           command: |
-            . venv/bin/activate
-            flask test
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+            if [[ "$HTTPCODE" -ne 200 ]]; then
+              echo "heroku app not responding, failing deploy" \
+              exit 1; \
+            fi
 
 workflows:
   version: 2
   build-test:
     jobs:
       - install
+      - back-deploy-heroku:
+          requires:
+            - install
